## servlet configuration
server:
  port: ${PORT:8083}

## application configuration
spring:
  application:
    name: ${APPLICATION_NAME:ignite-payment-service}
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  ## configure active profiles
#  profiles:
#    active: prod

## eureka server configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

# oauth2 security configuration
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8080/ignite-auth-service/oauth/check_token
    client:
      client-id: ignite-client
      client-secret: 1234

# oauth2 resource server configuration
oauth:
  resource-id: ${RESOURCE_ID:ignite_payment}

# cors configuration
accessControl:
  allowedOrigin: ${ALLOWED_ORIGIN:*}
  allowedMethods: ${ALLOWED_METHODS:GET, POST, PUT, PATCH, DELETE, OPTIONS}
  maxAge: ${MAX_AGE:3600}
  allowedHeaders: ${ALLOWED_HEADERS:*}

## Student-Microservice
student:
  baseUrl: ${STUDENT_BASE_URL:http://localhost:8080/ignite-student-service}
  studentInfoUrl: /api/v1/student/get/{studentId}
